# -*- coding: utf-8 -*-
"""word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUsRMDePYaUCEjovXuISCiyl5uH1qTLq
"""

!pip install gensim

import gensim

from gensim.models import Word2Vec, KeyedVectors

import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

vec_king

wv.most_similar('chess')

wv.similarity('batsman','cricket')

wv.most_similar(wv['king'] - wv['man'] + wv['woman'])

